version: "3.0"
services:
  # nginx:
  #   ports:
  #     - "3000:80"
  # node-app:
  #   build:
  #     context: ./api
  #     args: 
  #       NODE_ENV: development
  #   volumes:
  #     - .:/api
  #     - /api/node_modules
  #   environment:
  #     - NODE_ENV=developement
  #     - MONGO_USER=root
  #     - MONGO_PASSWORD=example
  #     - SESSION_SECRET=secret
  #   command: npm run dev
  frontend:
    image: imstepfan/frontend
    build:
      context: ./frontend
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example