version: "3.0"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: imstepfan/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  redis:
    image: redis
      
volumes:
  mongo-db: