version: "3.0"
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    image: imstepfan/node-app
    build:
      context: ./frontend
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js