version: "3.0"
services:
  # nginx:
  #   ports:
  #     - "3000:80"
  node-app:
    build:
      context: ./api
      args: 
        NODE_ENV: development
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      - NODE_ENV=developement
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example