version: "3.0"
services:
    # nginx:
    #   image: nginx:stable-alpine
    #   ports:
    #     - "3000:80"
    #   volumes:
    #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
     - ./src:/app/src
    

  # node-app:
  #   build: ./api
  #   restart: unless-stopped
  #   environment:
  #     - PORT=3000
  #   depends_on:
  #     - mongo
  #   networks:
  #     - backend
  #     - frontend

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  # redis:
  #   image: redis
      
# volumes:
#   mongo-db:
networks:
  # backend:
  frontend: